name: Maven Package and Docker Build

on:
  push:
    branches:
      - main  
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main  

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置 JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Maven 构建
      - name: Build with Maven
        run: mvn clean package -DskipTests -U

      # 4. 上传构建产物（可选）
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: fish-island-backend
          path: target/fish-island-backend-0.0.1-SNAPSHOT.jar

      # 5. 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t fish-island-backend:latest .

      # 6. 推送 Docker 镜像到 GitHub Packages
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag fish-island-backend:latest ghcr.io/${{ github.repository_owner }}/fish-island-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/fish-island-backend:latest
